#!/usr/bin/env bash
# ~/.git_template.local/hooks/pre-commit
# format-objc-hook
# pre-commit hook to check if any unformatted Objective-C files would be committed. Fails the check if so, and provides instructions.
#
# Copyright 2015 Square, Inc

IFS=$'\n'
export CDPATH=""
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source "$DIR"/lib/common-lib.sh

# Don't do anything unless a .clang-format file exists
[ -e ".clang-format" ] || exit 0

objc_files=$(objc_files_to_format "$1")
[ -z "$objc_files" ] && exit 0
# echo $objc_files
function format_objc() {
  success=0
  for file in $objc_files; do
    FILE=$file;
    if [ "${FILE#*.}" = "swift" ]
    then
        swift=1
        python "$DIR"/SwiftFormat/format.py --file "$file" --output "$file"
        success=1
    fi
  done

  for file in $objc_files; do
    FILE=$file;
    if [ "${FILE#*.}" != "swift" ]
    then
        difference=$("$DIR"/format-objc-file-dry-run.sh "$file" | diff "$file" - | wc -l)
        if [ $difference -gt 0 ]; then
          if [ $success -eq 0 ]; then
            # echo -e "🚸 Format and stage individual files:"
            echo -e "🚸 以 下 文 件 的 代 码 格 式 存 在 问 题:"
          fi
          "$DIR"/format-objc-file.sh "$file" 
          # This is what the dev can run to fixup an individual file
          # echo "\"$DIR\"/format-objc-file.sh '$file' && git add '$file';"
          echo "$file"
          success=1
        fi
    fi
  done
  if [ $success -gt 0 ]; then
      (echo -e "\n🔴 👆以 上 代 码 风 格 已 经 自 动 修 复 请 重 新 commit👆🔴" && success=1)
  fi
  # if [ $success -gt 0 ] && [ $swift -eq 0 ]; then
  #     echo -e "\n🚀  Format and stage all affected files:\n\t \"$DIR\"/format-objc-files.sh -s"
  #     (echo -e "\n🔴  您 提 交 的 代 码 风 格 不 符, 请 Git根目录 下 运行👆 上面👆 指令 修复.\n💔  或 是 您 可 以 使 用 git commit --no-verify 强 制 跳 过" && success=1)
  # fi
  # if [ $success -gt 0 ] && [ $swift -eq 1 ]; then
  #     echo -e "\n🚀  Format and stage all affected files:\n\t \"$DIR\"/format-objc-files.sh -s"
  #     (echo -e "\n🔴  您 提 交 的 代 码 风 格 中 含有 swift, 请 您 使 用 git commit --no-verify 强 制 跳 过" && success=1)
  #     success=0
  # fi
  return $success 
}
success=0
swift=0
format_objc
orgin=`git rev-parse --show-toplevel`

if [[ $DIR != $orgin ]]; then
  cd $orgin
  git add -u
fi
exit $success
